version: '3.3'
services:
  web:
    restart: always
    build: app
    volumes:
      - ./app:/app
    expose:
      - "5000"
    env_file:
      - ./environment.env
    command: gunicorn --log-level info app:app -b 0.0.0:5000 --name app --workers=9 --threads=4
    depends_on:
      - celery
    links:
      - celery
  celery:
    restart: always
    build: app
    volumes:
      - ./app:/app
    env_file:
      - ./environment.env
    command: celery worker -A app.celery --loglevel=info
    depends_on:
      - postgres
      - redis
  nginx:
    restart: always
    image: nginx:1.17.2
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./app/static:/app/static
    links:
      - web:web
    ports:
      - "8080:8080"
    depends_on:
      - web
  postgres:
    restart: always
    image: postgres:11.4
    volumes:
      - ./docker/postgres/db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - ./environment.env
  redis:
    restart: always
    image: redis:5.0.5
    volumes:
      - ./docker/redis/data:/data
    command: redis-server --requirepass redis --save 900 1 --save 300 10 --save 60 10000 --loglevel ${REDIS_LOGLEVEL:-warning}
    ports:
      - "6379:6379"
